# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k64qtLhp5BpP8sVUzKWDpuMnRcvC8y-N
"""

s = "Vanakkam da mapla!"
s.split()

"""Diameter of planet"""

planet = "X-460"
diameter = 12742
print("The diameter of {} is {} kilometers.". format(planet , diameter))

"""to print"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

"""Numpy Function"""

import numpy as np
a = np.zeros(10)
a

"""array"""

A = np.arange(20,35,2)
A

"""array"""

X = np.arange(0,9).reshape(3,3)
X

"""array"""

a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b),axis=0)

"""pandas"""

import pandas as pd
d = {"name":["aswini","swasthi","swetha"],"age":[20,20,20]}
df = pd.DataFrame(d)
df

"""frame display"""

P = pd.date_range(start='1-1-2023',end='10-2-2023')
for val in P:
  print(val)

"""Data frame"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists)
df